services:
  changying:
    image: ghcr.io/seekbaby/changying:latest
    container_name: changying
    ports:
      - "3000:3000"
    volumes:
      - changying_data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PORT=3000
      - DB_DIR=/app/data
      - OSS_REGION=oss-cn-shanghai
      - OSS_ACCESS_KEY_ID=LTAI5tAFbkRrRVNnTSwxuZAH
      - OSS_ACCESS_KEY_SECRET=pHF6mVCHRuntOUGqmUoZJRUvVX0SL
      - OSS_BUCKET=cy4
      - VOLCENGINE_APP_ID=9501334674
      - VOLCENGINE_TOKEN=y-fyQ7KRwmCm1H1Zhq74gquS3OY_wR0b
      - DEEPSEEK_API_KEY=sk-390367dae5e7418e8c38ab1e18860431

  watchtower:
    image: containrrr/watchtower
    container_name: changying_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup changying
    restart: unless-stopped

volumes:
  changying_data:
    name: changying_data
