services:
  changying:
    image: crpi-008b5xi3tkipemdi.cn-shanghai.personal.cr.aliyuncs.com/changying/changying-server:latest
    container_name: changying
    ports:
      - "3000:3000"
    volumes:
      - changying_data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PORT=3000
      - DB_DIR=/app/data

  watchtower:
    image: containrrr/watchtower
    container_name: changying_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup changying
    restart: unless-stopped

volumes:
  changying_data:
    name: changying_data
